classdef TetrisTetriminos
    %TETRISTETRIMINOS テトリミノの相対位置情報を作成する
    %   作成したテトリミノの相対位置は、GetTetriminoPosメンバ関数で呼び出す
    
    properties
        tetriminoNum
    end
    
    properties (Access = 'private')
        tetriminoPosList
    end
    
    methods
        %% コンストラクタ
        function obj = TetrisTetriminos()
            % I-テトリミノの相対位置
            obj.tetriminoPosList{1} = { ...
                {[0,0], [-1, 0], [1,0], [2,0]}, ...
                {[0,0], [ 0,-1], [0,1], [0,2]} ...
            };
            % O-テトリミノの相対位置
            obj.tetriminoPosList{2} = { ...
                {[0,0], [1,0], [1,-1], [0,-1]} ...
            };
            % S-テトリミノの相対位置
            obj.tetriminoPosList{3} = { ...
                {[0,0], [-1,0], [ 0,-1], [ 1,-1]}, ...
                {[0,0], [ 0,1], [-1, 0], [-1,-1]} ...
            };
            % Z-テトリミノの相対位置
            obj.tetriminoPosList{4} = { ...
                {[0,0], [1, 0], [ 0,-1], [-1,-1]}, ...
                {[0,0], [0,-1], [-1, 0], [-1, 1]} ...
            };
            % J-テトリミノの相対位置
            obj.tetriminoPosList{5} = { ...
                {[0,0], [-1, 0], [-1,-1], [ 1, 0]}, ...
                {[0,0], [ 0,-1], [ 1,-1], [ 0, 1]}, ...
                {[0,0], [ 1, 0], [ 1, 1], [-1, 0]}, ...
                {[0,0], [ 0, 1], [-1, 1], [ 0,-1]} ...
            };
            % L-テトリミノの相対位置
            obj.tetriminoPosList{6} = { ...
                {[0,0], [ 1, 0], [ 1,-1], [-1, 0]}, ...
                {[0,0], [ 0, 1], [ 1, 1], [ 0,-1]}, ...
                {[0,0], [-1, 0], [-1,-1], [ 1, 0]}, ...
                {[0,0], [ 0,-1], [-1,-1], [ 0, 1]} ...
            };
            % T-テトリミノの相対位置
            obj.tetriminoPosList{7} = { ...
                {[0,0], [-1, 0], [ 1, 0], [ 0,-1]}, ...
                {[0,0], [ 0,-1], [ 0, 1], [ 1, 0]}, ...
                {[0,0], [ 1, 0], [-1, 0], [ 0, 1]}, ...
                {[0,0], [ 0, 1], [ 0,-1], [-1, 0]} ...
            };
            % None
            obj.tetriminoPosList{8} = { ...
                {[0,0], [0,0], [0,0], [0,0]} ...
            };
            
            obj.tetriminoNum = length(obj.tetriminoPosList);
        end
        
        %% 指定したインデックスのブロックMatを取得
        function tetriminoPos = GetTetriminoPos(obj, tetriminoIndex)
            if 0 >= tetriminoIndex || obj.tetriminoNum < tetriminoIndex
                tetriminoPos = obj.tetriminoPosList{obj.tetriminoNum};
            else
                tetriminoPos = obj.tetriminoPosList{tetriminoIndex};
            end
        end
    end
end

