function [msParam] = GetMsParameter()

% ブロックのサイズ
blockSize = 30;

% 盤面サイズ
boardSize = struct( ...
    'width',  10, ...
    'height', 7 ...
);

% 盤面の描画サイズ
boardPanelSize = struct( ...
    'width',  boardSize.width * blockSize + 3, ...
    'height', boardSize.height * blockSize + 3, ...
    'margin', 30 ...
);

% ボム数の係数
bombRate = 0.1;

% ウィンドウのサイズ
windosSize = struct( ...
    'width',  (boardSize.width * blockSize) + 2*boardPanelSize.margin, ...
    'height', (boardSize.height * blockSize) + 2*boardPanelSize.margin ...
);

% ウィンドウ名
windowTitle = 'Minesweeper';

% マインスイーパーパラメータ
msParam = struct( ...
    'blockSize',      blockSize, ...
    'boardSize',      boardSize, ...
    'boardPanelSize', boardPanelSize, ...
    'bombRate',       bombRate, ...
    'windosSize',     windosSize, ...
    'windowTitle',    windowTitle ...
);

end